# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: ğŸ¡ é¦–é 
    url: /
    weight: 10
  - name: ğŸ—‚ï¸ æ–‡æª”
    url: docs/
    weight: 20
  - name: âœ ç­†è¨˜
    url: post/
    weight: 30
  - name: ğŸ¤– æ¡ˆä¾‹
    url: showcase/
    weight: 40
  - name: ğŸ‘ ç¤¾ç¾¤
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: éœ€è¦æ›´å¤šå”åŠ©?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "ğŸ‘ ç¤¾ç¾¤"
    pageRef: "/community"
    weight: 2
#  - identifier: hugoDocs
#    name: "Hugo Docs â†—"
#    url: "https://docs.hugoblox.com"
#    weight: 3
